
package com.co.linda.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Tue May 02 02:03:06 COT 2017
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "servicioLindaResponse", namespace = "http://services.linda.co.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servicioLindaResponse", namespace = "http://services.linda.co.com/")

public class ServicioLindaResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

